# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurviveLikeAStudentWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
